"""deleted admin_id column from status_change

Revision ID: 1f46c559d68f
Revises: 1fe5cf66f82b
Create Date: 2023-05-02 23:50:41.112389

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f46c559d68f'
down_revision = '1fe5cf66f82b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_change', schema=None) as batch_op:
        batch_op.drop_constraint('status_change_ibfk_2', type_='foreignkey')
        batch_op.drop_column('admin_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_change', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('status_change_ibfk_2', 'user', ['admin_id'], ['id'])

    # ### end Alembic commands ###
