"""addes admin_id column to ad

Revision ID: 1fe5cf66f82b
Revises: b0dcc09ed6ef
Create Date: 2023-05-02 23:49:33.572277

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1fe5cf66f82b'
down_revision = 'b0dcc09ed6ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', mysql.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['admin_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('admin_id')

    # ### end Alembic commands ###
