"""deleted status_change table

Revision ID: 67d4130dfafc
Revises: 1f46c559d68f
Create Date: 2023-05-03 15:17:21.951433

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '67d4130dfafc'
down_revision = '1f46c559d68f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status_change')
    with op.batch_alter_table('ad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_id', mysql.TINYINT(), nullable=False))
        batch_op.add_column(sa.Column('admin_message', mysql.TEXT(), nullable=True))
        batch_op.create_foreign_key(None, 'ad_status', ['status_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('admin_message')
        batch_op.drop_column('status_id')

    op.create_table('status_change',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status_id', mysql.TINYINT(), autoincrement=False, nullable=False),
    sa.Column('ad_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('set_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['ad.id'], name='status_change_ibfk_1'),
    sa.ForeignKeyConstraint(['status_id'], ['ad_status.id'], name='status_change_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
