"""admin_id is now nullable for ads

Revision ID: cab126fcf71d
Revises: cce57fceb568
Create Date: 2023-05-04 18:41:13.863240

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cab126fcf71d'
down_revision = 'cce57fceb568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad', schema=None) as batch_op:
        batch_op.alter_column('admin_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad', schema=None) as batch_op:
        batch_op.alter_column('admin_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
