"""deleted photos

Revision ID: cce57fceb568
Revises: 4f15d5a20e1c
Create Date: 2023-05-03 21:13:12.071408

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cce57fceb568'
down_revision = '4f15d5a20e1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('ad_photo')
    with op.batch_alter_table('ad', schema=None) as batch_op:
        batch_op.drop_column('license_plate_number')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.BLOB(), nullable=True))

    with op.batch_alter_table('ad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('license_plate_number', mysql.VARCHAR(length=20), nullable=True))

    op.create_table('ad_photo',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ad_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('photo', sa.BLOB(), nullable=False),
    sa.Column('is_main', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['ad.id'], name='ad_photo_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('message',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('receiver_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', mysql.TEXT(), nullable=False),
    sa.Column('sent_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], name='message_ibfk_2'),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name='message_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
